package vpn

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	osexec "os/exec"
	"path/filepath"
	"strings"
	"syscall"
)

// WarpBackend is the tool chain used to bring up a Cloudflare WARP tunnel.
type WarpBackend int

const (
	// WarpBackendNone means neither the wgcf chain nor warp-cli is
	// installed.
	WarpBackendNone WarpBackend = iota
	// WarpBackendWgcf brings the tunnel up from a wgcf-generated WireGuard
	// profile via wg-quick.
	WarpBackendWgcf
	// WarpBackendCli uses the official warp-cli daemon.
	WarpBackendCli
)

func (b WarpBackend) String() string {
	switch b {
	case WarpBackendWgcf:
		return "wgcf"
	case WarpBackendCli:
		return "warp-cli"
	default:
		return "none"
	}
}

// WarpServer returns the WARP entry merged into the server list. It has no
// OpenVPN config and no relay to probe: its probe short-circuits to
// working, and with a zero latency it always sorts behind measured relays.
func WarpServer() Server {
	return Server{
		HostName:    "warp",
		CountryLong: "Cloudflare WARP",
		IPAddr:      "engage.cloudflareclient.com",
		Source:      SourceWarp,
	}
}

// warpClient connects to Cloudflare WARP through wg-quick (wgcf profile)
// or the official warp-cli daemon.
type warpClient struct{}

// Connect implements Client.Connect for WARP: it emits the tunnel-up marker
// through out, then blocks until ctx is canceled, tearing the tunnel back
// down again. WARP never needs an OpenVPN config.
func (warpClient) Connect(ctx context.Context, server Server, out io.Writer) error {
	return WarpConnect(ctx, "", out, nil)
}

// ConnectDetached reports WARP's lack of background mode support: the
// supervisor relies on an OpenVPN management interface that WARP has no
// equivalent of.
func (warpClient) ConnectDetached(server Server, configPath, managementAddr string, logWriter io.Writer, sysProcAttr *syscall.SysProcAttr) (*osexec.Cmd, error) {
	return nil, errors.New("WARP does not support background (daemon) mode")
}

// WarpConnect brings up a Cloudflare WARP tunnel using the best available
// backend and blocks until ctx is canceled, tearing the tunnel back down.
// profileOverride forces the wgcf WireGuard profile path (default:
// <config>/wgcf/wgcf-profile.conf, created on first use). out, when
// non-nil, receives the tunnel-up marker that connectAttempt waits on.
// onUp, when non-nil, is invoked right after the tunnel reports up.
func WarpConnect(ctx context.Context, profileOverride string, out io.Writer, onUp func()) error {
	backend, err := DetectWarpBackend()
	if err != nil {
		return err
	}

	switch backend {
	case WarpBackendWgcf:
		profile, err := WarpWgcfProfile(profileOverride)
		if err != nil {
			return err
		}
		return warpConnectWgcf(ctx, profile, out, onUp)
	case WarpBackendCli:
		return warpConnectCli(ctx, out, onUp)
	}
	return errors.New("no WARP backend available")
}

// DetectWarpBackend picks the tool chain for WARP: wgcf + wg-quick when
// both are installed (wgcf alone cannot bring the tunnel up), otherwise
// the official warp-cli daemon, otherwise an error listing what to
// install.
func DetectWarpBackend() (WarpBackend, error) {
	if _, err := osexec.LookPath("wgcf"); err == nil {
		if _, err := osexec.LookPath("wg-quick"); err == nil {
			return WarpBackendWgcf, nil
		}
	}
	if _, err := osexec.LookPath("warp-cli"); err == nil {
		return WarpBackendCli, nil
	}
	return WarpBackendNone, errors.New("no WARP backend available: install the official client (cloudflare-warp, provides warp-cli) or wgcf + wireguard-tools (provides wg-quick)")
}

// WarpProfileDir returns the directory holding the wgcf account and
// profile artifacts: $XDG_CONFIG_HOME/wgcf (or ~/.config/wgcf).
func WarpProfileDir() (string, error) {
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "wgcf"), nil
}

// WarpWgcfProfile resolves the WireGuard profile to use: the override
// value when set, otherwise the default wgcf-profile.conf next to the wgcf
// account artifacts.
func WarpWgcfProfile(override string) (string, error) {
	if override != "" {
		return override, nil
	}
	dir, err := WarpProfileDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "wgcf-profile.conf"), nil
}

// warpConnectWgcf connects through a WireGuard profile generated by wgcf:
// it creates the profile on first use (wgcf register + wgcf generate),
// brings the tunnel up with wg-quick, reports it up, and tears it down
// again on interrupt.
func warpConnectWgcf(ctx context.Context, profile string, out io.Writer, onUp func()) error {
	if _, err := os.Stat(profile); err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if err := wgcfEnsureProfile(filepath.Dir(profile)); err != nil {
			return err
		}
	}

	up := osexec.CommandContext(ctx, "wg-quick", "up", profile)
	up.Stdout = out
	up.Stderr = out
	if err := up.Run(); err != nil {
		if os.Geteuid() != 0 {
			return fmt.Errorf("wg-quick up failed: %w (WARP needs root: try with sudo)", err)
		}
		return fmt.Errorf("wg-quick up failed: %w", err)
	}

	warpReportUp(out, onUp, profile)

	defer func() {
		down := osexec.Command("wg-quick", "down", profile)
		down.Stdout = out
		down.Stderr = out
		_ = down.Run()
	}()

	<-ctx.Done()
	return nil
}

// warpConnectCli connects through the official WARP daemon, registering a
// new device first when none exists yet, and disconnects on interrupt.
func warpConnectCli(ctx context.Context, out io.Writer, onUp func()) error {
	// An unregistered client reports "Registration missing"; create a
	// registration only in that case so existing WARP+ licenses survive.
	status, statusErr := osexec.CommandContext(ctx, "warp-cli", "status").CombinedOutput()
	if statusErr != nil || strings.Contains(strings.ToLower(string(status)), "missing") {
		register := osexec.CommandContext(ctx, "warp-cli", "registration", "new")
		register.Stdout = out
		register.Stderr = out
		if err := register.Run(); err != nil {
			return fmt.Errorf("warp-cli registration new failed: %w", err)
		}
	}

	connect := osexec.CommandContext(ctx, "warp-cli", "connect")
	connect.Stdout = out
	connect.Stderr = out
	if err := connect.Run(); err != nil {
		return fmt.Errorf("warp-cli connect failed: %w", err)
	}

	warpReportUp(out, onUp, "")

	defer func() {
		disconnect := osexec.Command("warp-cli", "disconnect")
		disconnect.Stdout = out
		disconnect.Stderr = out
		_ = disconnect.Run()
	}()

	<-ctx.Done()
	return nil
}

// warpReportUp emits the tunnel-up marker connectAttempt waits on and
// invokes onUp once the tunnel is actually established.
func warpReportUp(out io.Writer, onUp func(), profile string) {
	if out != nil {
		if profile != "" {
			fmt.Fprintf(out, "Connected to Cloudflare WARP (wgcf profile %s)\n", profile)
		} else {
			fmt.Fprintln(out, "Connected to Cloudflare WARP (warp-cli)")
		}
		// connectAttempt's trackedWriter closes its initDone signal on
		// this exact marker, the same one OpenVPN prints when a tunnel
		// initializes.
		fmt.Fprintln(out, "Initialization Sequence Completed")
	}
	if onUp != nil {
		onUp()
	}
}

// wgcfEnsureProfile creates a fresh WARP account and WireGuard profile in
// dir. wgcf writes wgcf-account.toml and wgcf-profile.conf relative to its
// working directory, so both steps run with dir as the working directory.
func wgcfEnsureProfile(dir string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	// wgcf register asks for consent to Cloudflare's ToS interactively;
	// --accept-tos keeps first-run provisioning non-interactive.
	register := osexec.Command("wgcf", "register", "--accept-tos")
	register.Dir = dir
	register.Stdout = os.Stdout
	register.Stderr = os.Stderr
	if err := register.Run(); err != nil {
		return fmt.Errorf("wgcf register failed: %w", err)
	}
	generate := osexec.Command("wgcf", "generate")
	generate.Dir = dir
	generate.Stdout = os.Stdout
	generate.Stderr = os.Stderr
	if err := generate.Run(); err != nil {
		return fmt.Errorf("wgcf generate failed: %w", err)
	}
	return nil
}
