# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    - go mod tidy
    - go get -v
    - rm -rf dist
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: KOUSSEMON-Aurel
    name: vpngate
  prerelease: auto
  mode: append
