package cmd

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/spf13/cobra"
)

func init() {
	warpCmd.Flags().StringVar(&flagWgcfConfig, "wgcf-config", "", "path to an existing wgcf WireGuard profile (default: <config>/wgcf/wgcf-profile.conf)")
	rootCmd.AddCommand(warpCmd)
}

// flagWgcfConfig overrides the wgcf WireGuard profile path used by the
// wgcf backend.
var flagWgcfConfig string

// warpBackend is the tool chain used to bring up a Cloudflare WARP tunnel.
type warpBackend int

const (
	warpBackendNone warpBackend = iota
	warpBackendWgcf             // wgcf profile + wg-quick
	warpBackendCli              // official warp-cli daemon
)

func (b warpBackend) String() string {
	switch b {
	case warpBackendWgcf:
		return "wgcf"
	case warpBackendCli:
		return "warp-cli"
	default:
		return "none"
	}
}

var warpCmd = &cobra.Command{
	Use:   "warp",
	Short: "Connect to Cloudflare WARP (wgcf + wg-quick, or warp-cli)",
	Long: "Connect to Cloudflare WARP. Uses wgcf to register an account, generate a\n" +
		"WireGuard profile and bring it up with wg-quick when both are installed;\n" +
		"otherwise falls back to the official warp-cli daemon. The wgcf path needs\n" +
		"root (it creates a tun interface).",
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runWarp()
	},
}

func runWarp() error {
	backend, err := detectWarpBackend()
	if err != nil {
		return err
	}
	fmt.Printf("WARP backend: %s\n", backend)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	switch backend {
	case warpBackendWgcf:
		profile, err := warpWgcfProfile()
		if err != nil {
			return err
		}
		return runWarpWgcf(ctx, profile)
	case warpBackendCli:
		return runWarpCli(ctx)
	}
	return errors.New("no WARP backend available")
}

// detectWarpBackend picks the tool chain for WARP: wgcf + wg-quick when
// both are installed (wgcf alone cannot bring the tunnel up), otherwise
// the official warp-cli daemon, otherwise an error listing what to
// install.
func detectWarpBackend() (warpBackend, error) {
	if _, err := exec.LookPath("wgcf"); err == nil {
		if _, err := exec.LookPath("wg-quick"); err == nil {
			return warpBackendWgcf, nil
		}
	}
	if _, err := exec.LookPath("warp-cli"); err == nil {
		return warpBackendCli, nil
	}
	return warpBackendNone, errors.New("no WARP backend available: install the official client (cloudflare-warp, provides warp-cli) or wgcf + wireguard-tools (provides wg-quick)")
}

// warpProfileDir returns the directory holding the wgcf account and
// profile artifacts: $XDG_CONFIG_HOME/wgcf (or ~/.config/wgcf).
func warpProfileDir() (string, error) {
	dir, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "wgcf"), nil
}

// warpWgcfProfile resolves the WireGuard profile to use: the --wgcf-config
// value when set, otherwise the default wgcf-profile.conf next to the wgcf
// account artifacts.
func warpWgcfProfile() (string, error) {
	if flagWgcfConfig != "" {
		return flagWgcfConfig, nil
	}
	dir, err := warpProfileDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "wgcf-profile.conf"), nil
}

// runWarpWgcf connects through a WireGuard profile generated by wgcf: it
// creates the profile on first use (wgcf register + wgcf generate), brings
// the tunnel up with wg-quick, verifies it end-to-end, and tears it down
// again on interrupt.
func runWarpWgcf(ctx context.Context, profile string) error {
	if _, err := os.Stat(profile); err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if err := wgcfEnsureProfile(filepath.Dir(profile)); err != nil {
			return err
		}
	}

	up := exec.CommandContext(ctx, "wg-quick", "up", profile)
	up.Stdout = os.Stdout
	up.Stderr = os.Stderr
	if err := up.Run(); err != nil {
		if os.Geteuid() != 0 {
			return fmt.Errorf("wg-quick up failed: %w (WARP needs root: try with sudo)", err)
		}
		return fmt.Errorf("wg-quick up failed: %w", err)
	}

	fmt.Printf("Connected to Cloudflare WARP (wgcf profile %s)\n", profile)
	defer func() {
		down := exec.Command("wg-quick", "down", profile)
		down.Stdout = os.Stdout
		down.Stderr = os.Stderr
		_ = down.Run()
	}()

	verifyTunnel(func(s string) { fmt.Println(s) })

	<-ctx.Done()
	return nil
}

// runWarpCli connects through the official WARP daemon, registering a new
// device first when none exists yet, and disconnects on interrupt.
func runWarpCli(ctx context.Context) error {
	// An unregistered client reports "Registration missing"; create a
	// registration only in that case so existing WARP+ licenses survive.
	status, statusErr := exec.CommandContext(ctx, "warp-cli", "status").CombinedOutput()
	if statusErr != nil || strings.Contains(strings.ToLower(string(status)), "missing") {
		register := exec.CommandContext(ctx, "warp-cli", "registration", "new")
		register.Stdout = os.Stdout
		register.Stderr = os.Stderr
		if err := register.Run(); err != nil {
			return fmt.Errorf("warp-cli registration new failed: %w", err)
		}
	}

	connect := exec.CommandContext(ctx, "warp-cli", "connect")
	connect.Stdout = os.Stdout
	connect.Stderr = os.Stderr
	if err := connect.Run(); err != nil {
		return fmt.Errorf("warp-cli connect failed: %w", err)
	}

	fmt.Println("Connected to Cloudflare WARP (warp-cli)")
	defer func() {
		disconnect := exec.Command("warp-cli", "disconnect")
		disconnect.Stdout = os.Stdout
		disconnect.Stderr = os.Stderr
		_ = disconnect.Run()
	}()

	verifyTunnel(func(s string) { fmt.Println(s) })

	<-ctx.Done()
	return nil
}

// wgcfEnsureProfile creates a fresh WARP account and WireGuard profile in
// dir. wgcf writes wgcf-account.toml and wgcf-profile.conf relative to its
// working directory, so both steps run with dir as the working directory.
func wgcfEnsureProfile(dir string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	register := exec.Command("wgcf", "register")
	register.Dir = dir
	register.Stdout = os.Stdout
	register.Stderr = os.Stderr
	if err := register.Run(); err != nil {
		return fmt.Errorf("wgcf register failed: %w", err)
	}
	generate := exec.Command("wgcf", "generate")
	generate.Dir = dir
	generate.Stdout = os.Stdout
	generate.Stderr = os.Stderr
	if err := generate.Run(); err != nil {
		return fmt.Errorf("wgcf generate failed: %w", err)
	}
	return nil
}
