// Command genland rasterizes the Natural Earth 110m land polygons into a
// 1-degree land mask and emits it as internal/tui/land_raster.go so the TUI's
// globe needs no external data at runtime.
//
// Usage:
//
//	go run ./tools/genland [geojson-path]
//
// If geojson-path is omitted the tool downloads ne_110m_land from the
// Natural Earth GitHub repository.
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	geoURL  = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
	cols    = 360
	rows    = 180
	outPath = "internal/tui/land_raster.go"
)

type geometry struct {
	Type        string          `json:"type"`
	Coordinates json.RawMessage `json:"coordinates"`
	Geometries  []geometry      `json:"geometries"`
}

type feature struct {
	Geometry geometry `json:"geometry"`
}

type featureCollection struct {
	Features []feature `json:"features"`
}

// ring is a closed polygon ring of [lon, lat] pairs.
type ring [][2]float64

// rasterize fills land[j*cols+i] using scanline even-odd rasterisation.
// Every ring toggles the cells it covers, so holes (rings inside an outer
// ring) flip land back to ocean. Landmasses in the 110m dataset are disjoint,
// so rings from different features never overlap.
func rasterize(rings []ring) []bool {
	land := make([]bool, rows*cols)
	for _, r := range rings {
		n := len(r)
		if n < 3 {
			continue
		}
		minLat, maxLat := 90.0, -90.0
		for _, p := range r {
			if p[1] < minLat {
				minLat = p[1]
			}
			if p[1] > maxLat {
				maxLat = p[1]
			}
		}
		jMin := int(mathFloor(89.5 - maxLat))
		if jMin < 0 {
			jMin = 0
		}
		jMax := int(mathCeil(89.5 - minLat))
		if jMax > rows-1 {
			jMax = rows - 1
		}
		for j := jMin; j <= jMax; j++ {
			lat := 90 - float64(j) - 0.5
			var xs []float64
			for k := 0; k < n; k++ {
				a, b := r[k], r[(k+1)%n]
				if (a[1] > lat) == (b[1] > lat) {
					continue
				}
				x := a[0] + (lat-a[1])*(b[0]-a[0])/(b[1]-a[1])
				xs = append(xs, x)
			}
			sort.Float64s(xs)
			for k := 0; k+1 < len(xs); k += 2 {
				i0 := int(mathFloor(xs[k] + 180))
				i1 := int(mathCeil(xs[k+1] + 180))
				for i := i0; i < i1; i++ {
					ii := ((i % cols) + cols) % cols
					land[j*cols+ii] = !land[j*cols+ii]
				}
			}
		}
	}
	return land
}

func mathFloor(f float64) float64 {
	g := float64(int(f))
	if f < g {
		return g - 1
	}
	return g
}

func mathCeil(f float64) float64 {
	g := float64(int(f))
	if f > g {
		return g + 1
	}
	return g
}

// collectRings flattens Polygon / MultiPolygon / GeometryCollection features
// into closed rings, keeping track of landmass id so holes only toggle cells
// already filled by their own outer ring.
func collectRings(g geometry, out *[]ring) {
	switch g.Type {
	case "Polygon":
		var polys [][][2]float64
		if err := json.Unmarshal(g.Coordinates, &polys); err != nil {
			panic(err)
		}
		for _, poly := range polys {
			*out = append(*out, poly)
		}
	case "MultiPolygon":
		var polys [][][][2]float64
		if err := json.Unmarshal(g.Coordinates, &polys); err != nil {
			panic(err)
		}
		for _, poly := range polys {
			for _, ring := range poly {
				*out = append(*out, ring)
			}
		}
	case "GeometryCollection":
		for _, sub := range g.Geometries {
			collectRings(sub, out)
		}
	}
}

func main() {
	src := ""
	if len(os.Args) > 1 {
		src = os.Args[1]
	}

	var data []byte
	var err error
	if src != "" {
		data, err = os.ReadFile(src)
	} else {
		data, err = download(geoURL)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "genland:", err)
		os.Exit(1)
	}

	var fc featureCollection
	if err := json.Unmarshal(data, &fc); err != nil {
		fmt.Fprintln(os.Stderr, "genland: parse:", err)
		os.Exit(1)
	}

	var rings []ring
	for _, f := range fc.Features {
		collectRings(f.Geometry, &rings)
	}

	land := rasterize(rings)

	count := 0
	for _, b := range land {
		if b {
			count++
		}
	}
	fmt.Printf("rings=%d land_cells=%d (%.1f%%)\n", len(rings), count, 100*float64(count)/(rows*cols))

	bits := make([]byte, rows*cols/8)
	for i, b := range land {
		if b {
			bits[i/8] |= 1 << (7 - uint(i%8))
		}
	}
	encoded := base64.StdEncoding.EncodeToString(bits)

	// Wrap the base64 string into 100-column source lines.
	var b strings.Builder
	for len(encoded) > 100 {
		b.WriteString("\t\"" + encoded[:100] + "\" +\n")
		encoded = encoded[100:]
	}
	b.WriteString("\t\"" + encoded + "\"")
	body := b.String()

	out := fmt.Sprintf(`// Code generated by tools/genland from Natural Earth 110m land
// (https://github.com/nvkelso/natural-earth-vector). DO NOT EDIT.
//
// landRaster is a 1-degree land mask, 180 rows (89.5N..89.5S) by 360 columns
// (179.5W..179.5E), bit-packed MSB-first: bit set means land. It is decoded
// once at first use by landAt.
package tui

var landRasterEncoded = %s
`, body)

	formatted, err := format.Source([]byte(out))
	if err != nil {
		fmt.Fprintln(os.Stderr, "genland: format:", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "genland:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "genland:", err)
		os.Exit(1)
	}
	fmt.Println("wrote", outPath)
}

func download(url string) ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download %s: http %d", url, resp.StatusCode)
	}
	return io.ReadAll(resp.Body)
}
